development: &defaults
  adapter: postgresql
  encoding: utf8
  database: <%= ENV['POSTGRES_DEV_DB'] %>
  username: <%= ENV['POSTGRES_DEV_USER'] %>
  password: <%= ENV['POSTGRES_DEV_PASSWORD'].presence %>
  host: <%= ENV['POSTGRES_DEV_HOST'] %>
  pool: 100
  timeout: 5000
  encoding: utf8
  collation: ru_RU.UTF-8
  ctype: ru_RU.UTF-8
  template: template0

production:
  <<: *defaults

test:
  <<: *defaults
  database: <%= ENV['POSTGRES_TEST_DB'] %><%=ENV['TEST_ENV_NUMBER'] %>
  username: <%= ENV['POSTGRES_TEST_USER'] %>
  password: <%= ENV['POSTGRES_TEST_PASSWORD'].presence %>
  host: <%= ENV['POSTGRES_TEST_HOST'] %>
