---
# For more options, see https://docs.honeybadger.io/lib/ruby/gem-reference/configuration

api_key: 'hbp_tObQMWZaPeNe3kVaGAUZVUc8BAscDg3WQff7'

# The environment your app is running in.
env: "<%= Rails.env %>"

# The absolute path to your project folder.
root: "<%= Rails.root.to_s %>"

# Honeybadger won't report errors in these environments.
development_environments:
- test
- development
- cucumber

exceptions:
  ignore:
    - AbstractController::ActionNotFound
    - ActionController::InvalidAuthenticityToken
    - ActionController::ParameterMissing
    - ActionController::RoutingError
    - ActionController::UnknownFormat
    - ActionController::UnknownHttpMethod
    - ActionController::BadRequest
    - ActionDispatch::RemoteIp::IpSpoofAttackError
    - ActiveRecord::PreparedStatementCacheExpired
    - ActiveRecord::RecordNotFound
    - CanCan::AccessDenied
    - I18n::InvalidLocale
    - Unicorn::ClientShutdown
    - AgeRestricted
    - RknBanned
    - MismatchedEntries
    - InvalidEpisodesError
    - CopyrightedResource
    - Net::SMTPServerBusy
    - Net::SMTPFatalError
    - Interrupt
    - Apipie::ParamMissing
    - InvalidIdError
    - InvalidParameterError
    - EmptyContentError
    - MalParser::RecordNotFound
    - Errors::NotIdentifiedByImageMagickError
    - Sidekiq::Shutdown
    - Terrapin::ExitStatusError
    - ActionDispatch::Http::MimeNegotiation::InvalidType

# By default, Honeybadger won't report errors in the development_environments.
# You can override this by explicitly setting report_data to true or false.
# report_data: true

# The current Git revision of your project. Defaults to the last commit hash.
# revision: null

# Enable verbose debug logging (useful for troubleshooting).
debug: false
