name: 'RSpec CI'
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
jobs:
  # rubocop:
  #   name: Rubocop
  #   runs-on: 'ubuntu-20.04'
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: '3.0'
  #     - run: script/update_rubygems_and_install_bundler
  #     - run: bundle install --standalone
  #     - run: bundle binstubs --all
  #     - run: script/run_rubocop

  RSpec:
    # strategy:
    #   matrix:
    #     node-version: [14.x]
    #     redis-version: [6]
    runs-on: 'ubuntu-22.04'
    services:
      postgres:
        image: postgres:10.5-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    env:
      POSTGRES_TEST_USER: postgres
      POSTGRES_TEST_PASSWORD: postgres
      POSTGRES_TEST_DB: github-actions
      RAILS_ENV: test
      CI_SERVER: yes
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libvips imagemagick libjpeg-progs
      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 6
          # redis-version: ${{ matrix.redis-version }}
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          # node-version: ${{ matrix.node-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set up database schema
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load
      - name: Run tests
        run: bundle exec rspec --format progress
